version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: backend-app:latest
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb

  frontend:
    image: frontend-app:latest
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
