kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: my-app
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
                        
