kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <your image name>:<tag of image>
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80



